modfying testing scripts

diff --git a/rel_6/Testing/AtlasConditionsTests/AtlasConditionsTests b/rel_6/Testing/AtlasConditionsTests/AtlasConditionsTests
--- a/rel_6/Testing/AtlasConditionsTests/AtlasConditionsTests
+++ b/rel_6/Testing/AtlasConditionsTests/AtlasConditionsTests
@@ -1,23 +1,30 @@
 #!/bin/sh
-
-#!/bin/sh
 export AtlasVersion=AtlasConditions
+echo -e "\e[1;34m${AtlasVersion} \e[0m" >> PASSorFAIL
 function SuccessOrNot {
-        if [ $1 -eq 0 ]; then
-          echo "$(tput setaf 2) $2 succeeded" >> PASSorFAIL
+	if [ $1 -eq 0 ]; then
+          echo -e "\e[1;32m$2 succeeded \e[0m" >> ../PASSorFAIL
         else
-          echo "$(tput setaf 1) $2 FAILED" >> PASSorFAIL
+          echo -e "\e[1;31m$2 FAILED \e[0m" >> ../PASSorFAIL
         fi
 }
 
 alias echoC='echo "$(tput setaf 1)$(tput setab 7) Starting new test... $(tput sgr 0)"'
-alias athena.py='timeout 10 athena.py'
+#alias athena.py='timeout 100 athena.py'
 
 function runTest {
         echoC
-        athena.py $1
+        newdir=`cut -d/ -f1 <<< $1`
+        runName=`cut -d/ -f2 <<< $1`
+        echo ${newdir}
+#        mkdir ${newdir}
+        cd ${newdir}
+#        ln -s /home/jwsmith/ANA/rel_6/Testing/Database_fromLxplus/* .
+        athena.py $1 > >(tee ${runName}.log) 2>&1 ; ( exit ${PIPESTATUS[0]} )
         SuccessOrNot $? $1
+        cd ..
 }
 
 runTest InDetGeometryValidation/ReadTRT_DetectorElements_jobOptions.py
 runTest InDetGeometryValidation/ReadSiDetectorElements_jobOptions.py
+
diff --git a/rel_6/Testing/AtlasEventTests/AtlasEventTests b/rel_6/Testing/AtlasEventTests/AtlasEventTests
--- a/rel_6/Testing/AtlasEventTests/AtlasEventTests
+++ b/rel_6/Testing/AtlasEventTests/AtlasEventTests
@@ -1,23 +1,38 @@
 #!/bin/sh
-#!/bin/sh
-export AtlasVersion=AtlasCore
+export AtlasVersion=AtlasEvent
+echo -e "\e[1;34m${AtlasVersion} \e[0m" >> PASSorFAIL
 function SuccessOrNot {
         if [ $1 -eq 0 ]; then
-          echo "$(tput setaf 2) $2 succeeded" >> PASSorFAIL
+          echo -e "\e[1;32m$2 succeeded \e[0m" >> ../PASSorFAIL
         else
-          echo "$(tput setaf 1) $2 FAILED" >> PASSorFAIL
+          echo -e "\e[1;31m$2 FAILED \e[0m" >> ../PASSorFAIL
         fi
 }
 
-alias athena.py='timeout 100 athena.py'
+alias echoC='echo "$(tput setaf 1)$(tput setab 7) Starting new test... $(tput sgr 0)"'
+#alias athena.py='timeout 100 athena.py'
 
 function runTest {
-        echo "$(tput setaf 1)$(tput setab 7) Starting new test: $1 $(tput sgr 0)"
-        athena.py $1
-        SuccessOrNot $? $1
+        echoC
+        newdir=`cut -d/ -f1 <<< $1`
+	runName=`cut -d/ -f2 <<< $1`
+        echo ${newdir}
+#        mkdir ${newdir}
+	cd ${newdir}	
+#        ln -s /home/jwsmith/ANA/rel_6/Testing/Database_fromLxplus/* .
+	if [ ${runName} == "MultiplePass_test.py" ] || [ ${runName} == "MixingEventSelector_test.py" ]
+        then
+		athena.py ${runName} > >(tee ${runName}.log) 2>&1 ; ( exit ${PIPESTATUS[0]} )
+	else
+		athena.py $1 > >(tee ${runName}.log) 2>&1 ; ( exit ${PIPESTATUS[0]} )
+        fi
+	SuccessOrNot $? $1
+        cd ..
 }
 runTest AthenaDBTestRec/ReadRefDBExample.py
+
 runTest AthenaServices/MultiplePass_test.py
+
 runTest EventLoopTest/ByteStreamReadTest.py
 runTest AthenaServices/MixingEventSelector_test.py
 
diff --git a/rel_6/Testing/AtlasReconstructionTests/AtlasReconstructionTests b/rel_6/Testing/AtlasReconstructionTests/AtlasReconstructionTests
--- a/rel_6/Testing/AtlasReconstructionTests/AtlasReconstructionTests
+++ b/rel_6/Testing/AtlasReconstructionTests/AtlasReconstructionTests
@@ -1,98 +1,107 @@
 #!/bin/sh
 export AtlasVersion=AtlasReconstruction
+echo -e "\e[1;34m${AtlasVersion} \e[0m" >> PASSorFAIL
 function SuccessOrNot {
         if [ $1 -eq 0 ]; then
-          echo "$(tput setaf 2) $2 succeeded" >> PASSorFAIL
+          echo -e "\e[1;32m$2 succeeded \e[0m" >> ../PASSorFAIL
         else
-          echo "$(tput setaf 1) $2 FAILED" >> PASSorFAIL
+          echo -e "\e[1;31m$2 FAILED \e[0m" >> ../PASSorFAIL
         fi
 }
 
 alias echoC='echo "$(tput setaf 1)$(tput setab 7) Starting new test... $(tput sgr 0)"'
-alias athena.py='timeout 10 athena.py'
-##############################################################
+#alias athena.py='timeout 100 athena.py'
 function runTest {
         echoC
-        athena.py $1
+        newdir=`cut -d/ -f1 <<< $1`
+        runName=`cut -d/ -f2 <<< $1`
+        echo ${newdir}
+#        mkdir ${newdir}
+#        ln -s /home/jwsmith/ANA/rel_6/Testing/Database_fromLxplus/* .
+        if [ ${runName} == "jobOptions_RecExCommon_NewConfig.py" ]
+        then
+ 		cd InDetExperimentalReco
+                athena.py ${runName} > >(tee ${runName}.log) 2>&1 ; ( exit ${PIPESTATUS[0]} )
+        else
+        	cd ${newdir}
+	        athena.py $1 > >(tee ${runName}.log) 2>&1 ; ( exit ${PIPESTATUS[0]} )
+        fi
         SuccessOrNot $? $1
+        cd ..
 }
 
-runTest CaloRecEx/CaloRecEx_topOptions.py
-runTest CaloRecEx/CaloRecEx_topOptions.py
-runTest InDetExperimentalReco/jobOptions_RecExCommon_masking.py
-runTest InDetExperimentalReco/jobOptions_RecExCommon_masking.py
+
+
+###############################################################
+#runTest CaloRecEx/CaloRecEx_topOptions.py
+#runTest jobOptions_RecExCommon_NewConfig.py
+##runTest InDetExperimentalReco/jobOptions_RecExCommon_masking.py
 ##############################################################
 
 function runTestmem {
         echoC
-        athena.py -c "jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py $1
+        newdir=`cut -d/ -f1 <<< $1`
+        runName=`cut -d/ -f2 <<< $1`
+        echo ${newdir}
+        mkdir ${newdir}
+        cd ${newdir}
+#        ln -s /home/jwsmith/ANA/rel_6/Testing/Database_fromLxplus/* .
+        if [ ${runName} == "jobOptions_RecExCommon_NewConfig.py" ]
+        then
+                athena.py ${runName} > >(tee ${runName}.log) 2>&1 ; ( exit ${PIPESTATUS[0]} )
+        else
+                athena.py -c "jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py $1 > >(tee ${runName}.log) 2>&1 ; ( exit ${PIPESTATUS[0]} )
+        fi
         SuccessOrNot $? $1
+        cd ..
 }
 
-runTestmem RecExRecoTest/RecExRecoTest_RTT_empty.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_empty.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_forwarddet.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_forwarddet.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_calo.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_calo.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_id.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_id.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_muon.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_muon.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_idmuon.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_idmuon.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_idcalo.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_idcalo.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_idmuoncalo.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_idmuoncalo.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_idcaloegamma.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_idcaloegamma.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_idmuoncalomuoncomb.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_idmuoncalomuoncomb.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_calomax.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_calomax.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_idmuonmax.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_idmuonmax.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_idcalomax.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_idcalomax.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_esd.py
-runTestmem RecExRecoTest/RecExRecoTest_RTT_esd.py
+#runTestmem RecExRecoTest/RecExRecoTest_RTT_empty.py
+#runTestmem RecExRecoTest/RecExRecoTest_RTT_forwarddet.py
+#runTestmem RecExRecoTest/RecExRecoTest_RTT_calo.py
+#runTestmem RecExRecoTest/RecExRecoTest_RTT_id.py
+runTestmem RecExRecoTest/RecExRecoTest_RTT_muon.py ##One we were working on 
+#runTestmem RecExRecoTest/RecExRecoTest_RTT_idmuon.py
+#runTestmem RecExRecoTest/RecExRecoTest_RTT_idcalo.py
+#runTestmem RecExRecoTest/RecExRecoTest_RTT_idmuoncalo.py ## But this one finds /GLOBAL/TrackingGeo/LayerMaterialV2
+#runTestmem RecExRecoTest/RecExRecoTest_RTT_idcaloegamma.py
+#runTestmem RecExRecoTest/RecExRecoTest_RTT_idmuoncalomuoncomb.py
+#runTestmem RecExRecoTest/RecExRecoTest_RTT_calomax.py
+#runTestmem RecExRecoTest/RecExRecoTest_RTT_idmuonmax.py
+#runTestmem RecExRecoTest/RecExRecoTest_RTT_idcalomax.py
+#runTestmem RecExRecoTest/RecExRecoTest_RTT_esd.py
 ##############################################################
-
-function runTestesd1 {
-        echoC
-        athena.py -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True ; rec.noESDTrigger=True " AthenaCommon/MemTraceInclude.py $1
-        SuccessOrNot $? $1
-}
-
-function runTestesd2 {
-        echoC
-	athena.py -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True ; rec.noESDTrigger=True ; rec.doESD.set_Value_and_Lock(True) ; jp.AthenaCommonFlags.PoolESDOutput='reco_ESD.pool.root' " AthenaCommon/MemTraceInclude.py $1
-        SuccessOrNot $? $1
-}
-
-runTestesd1 RecExCommon/esdtoesd.py
-runTestesd1 RecExCommon/esdtoesd.py
-runTestesd2 RecExCommon/esdtoesd.py
-runTestesd2 RecExCommon/esdtoesd.py
-##############################################################
-
-function runTestMCNatlo {
-        echoC
-	athena.py -c "jp.AthenaCommonFlags.EvtMax=2; jp.AthenaCommonFlags.SkipEvents=3 ; rec.AutoConfiguration=['everything']; rec.doDetailedAuditor=True ; rec.doNameAuditor=True ; jp.AthenaCommonFlags.PoolRDOInput=['root://eosatlas//eos/atlas/atlascerngroupdisk/phys-rig/pileupSamples/LS1Samples/valid1.105200.McAtNloJimmy_CT10_ttbar_LeptonFilter.recon.RDO.e1565_s1499_s1504_r4242_tid01185596_00/RDO.01185596._000001.pool.root.1']" AthenaCommon/MemTraceInclude.py $1
-        SuccessOrNot $? $1
-}
-
-runTestMCNatlo RecExRecoTest/RecExRecoTest_RTT_esdlowlumi.py
-runTestMCNatlo RecExRecoTest/RecExRecoTest_RTT_esdlowlumi.py
-##############################################################
-
-function runTestJetTau {
-        echoC
-        athena.py -c 'jp.AthenaCommonFlags.FilesInput=["/afs/cern.ch/atlas/project/rig/referencefiles/dataStreams_high_mu/data12_8TeV/data12_8TeV.00209109.physics_JetTauEtmiss.merge.RAW._lb0186._SFO-1._0001.1"];rec.doTrigger.set_Value_and_Lock(False);rec.doDPD.set_Value_and_Lock(True);rec.doNameAuditor=True;jp.AthenaCommonFlags.PoolESDOutput="data_ESD.pool.root"' $1 
-        SuccessOrNot $? $1
-}
-
-runTestJetTau RecExCommon/rdotoesdnotrigger.py
-runTestJetTau RecExCommon/rdotoesdnotrigger.py
-##############################################################
+#
+#function runTestesd1 {
+#        echoC
+#        athena.py -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True ; rec.noESDTrigger=True " AthenaCommon/MemTraceInclude.py $1
+#        SuccessOrNot $? $1
+#}
+#
+#function runTestesd2 {
+#        echoC
+#	athena.py -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True ; rec.noESDTrigger=True ; rec.doESD.set_Value_and_Lock(True) ; jp.AthenaCommonFlags.PoolESDOutput='reco_ESD.pool.root' " AthenaCommon/MemTraceInclude.py $1
+#        SuccessOrNot $? $1
+#}
+#
+#runTestesd1 RecExCommon/esdtoesd.py
+#runTestesd2 RecExCommon/esdtoesd.py
+###############################################################
+#
+#function runTestMCNatlo {
+#        echoC
+#	athena.py -c "jp.AthenaCommonFlags.EvtMax=2; jp.AthenaCommonFlags.SkipEvents=3 ; rec.AutoConfiguration=['everything']; rec.doDetailedAuditor=True ; rec.doNameAuditor=True ; jp.AthenaCommonFlags.PoolRDOInput=['root://eosatlas//eos/atlas/atlascerngroupdisk/phys-rig/pileupSamples/LS1Samples/valid1.105200.McAtNloJimmy_CT10_ttbar_LeptonFilter.recon.RDO.e1565_s1499_s1504_r4242_tid01185596_00/RDO.01185596._000001.pool.root.1']" AthenaCommon/MemTraceInclude.py $1
+#        SuccessOrNot $? $1
+#}
+#
+#runTestMCNatlo RecExRecoTest/RecExRecoTest_RTT_esdlowlumi.py
+###############################################################
+#
+#function runTestJetTau {
+#        echoC
+#        athena.py -c 'jp.AthenaCommonFlags.FilesInput=["/afs/cern.ch/atlas/project/rig/referencefiles/dataStreams_high_mu/data12_8TeV/data12_8TeV.00209109.physics_JetTauEtmiss.merge.RAW._lb0186._SFO-1._0001.1"];rec.doTrigger.set_Value_and_Lock(False);rec.doDPD.set_Value_and_Lock(True);rec.doNameAuditor=True;jp.AthenaCommonFlags.PoolESDOutput="data_ESD.pool.root"' $1 
+#        SuccessOrNot $? $1
+#}
+#
+#runTestJetTau RecExCommon/rdotoesdnotrigger.py
+###############################################################
