testing scripts

diff --git a/rel_6/Testing/AtlasAnalysisTests/AtlasAnalysisTests b/rel_6/Testing/AtlasAnalysisTests/AtlasAnalysisTests
--- a/rel_6/Testing/AtlasAnalysisTests/AtlasAnalysisTests
+++ b/rel_6/Testing/AtlasAnalysisTests/AtlasAnalysisTests
@@ -1,124 +1,101 @@
 #!/bin/sh
 export AtlasVersion=AtlasAnalysis
+function SuccessOrNot {
+        if [ $1 -eq 0 ]; then
+          echo "$(tput setaf 2) $2 succeeded" >> PASSorFAIL
+        else
+          echo "$(tput setaf 1) $2 FAILED" >> PASSorFAIL
+        fi
+}
+
 alias echoC='echo "$(tput setaf 1)$(tput setab 7) Starting new test... $(tput sgr 0)"'
-echoC
-athena.py UserDataExamples/UserDataExamples_Writer.py
-echoC
-athena.py UserDataExamples/UserDataExamples_Writer.py
-echoC
-athena.py UserDataExamples/UserDataExamples_Reader.py
-echoC
-athena.py UserDataExamples/UserDataExamples_Reader.py
-echoC
-athena.py InDetAlignExample/AlignmentATNSimple.py
-echoC
-athena.py InDetAlignExample/AlignmentATNSimple.py
-echoC
-athena.py InDetMonitoringATN/jobOptions_cosmics.py
-echoC
-athena.py InDetMonitoringATN/jobOptions_cosmics.py
-echoC
-athena.py  -c 'doMonitoring=False; runAccumulator=False; doLArCalibDataQuality=True; GainList=["HIGH"]; PartitionType="EMB"; Partition="EB-EMBA"; PartitionTypeGeneric="EMBPS"; RunNumberList=[174585]; RunNumberFlag=int(RunNumberList[0]); InputDir=" "; FullFileName=["/afs/cern.ch/user/l/larcalib/w0/Test/data11_calib.00174585.calibration_LArElec-Pedestal-7s-High-BarrelPS.daq.RAW._lb0000._EB-EMBA._0001.data"]; GroupingType="ExtendedSubDetector" ' LArCalibProcessing/UseLArExtendedSubDetGrouping.py  LArCalibProcessing/LArCalib_PedestalAutoCorr_jobOptions.py LArCalibProcessing/LArCalib_PedestalAutoCorr_testing.py
-echoC
-athena.py  -c 'doMonitoring=False; runAccumulator=False; doLArCalibDataQuality=True; GainList=["HIGH"]; PartitionType="EMB"; Partition="EB-EMBA"; PartitionTypeGeneric="EMBPS"; RunNumberList=[174585]; RunNumberFlag=int(RunNumberList[0]); InputDir=" "; FullFileName=["/afs/cern.ch/user/l/larcalib/w0/Test/data11_calib.00174585.calibration_LArElec-Pedestal-7s-High-BarrelPS.daq.RAW._lb0000._EB-EMBA._0001.data"]; GroupingType="ExtendedSubDetector" ' LArCalibProcessing/UseLArExtendedSubDetGrouping.py  LArCalibProcessing/LArCalib_PedestalAutoCorr_jobOptions.py LArCalibProcessing/LArCalib_PedestalAutoCorr_testing.py
-echoC
-athena.py  -c 'doMonitoring=False; doLArCalibDataQuality=True; CorrectBadChannels=True; ApplyAdHocCorrection=False; GainList=["HIGH"]; PartitionType="EMB"; Partition="EB-EMBA"; PartitionTypeGeneric="EMBPS"; RunNumberList=[174586]; RunNumberFlag=int(RunNumberList[0]); InputDir=" "; FullFileName=["/afs/cern.ch/user/l/larcalib/w0/Test/data11_calib.00174586.calibration_LArElec-Ramp-7s-High-BarrelPS.daq.RAW._lb0000._EB-EMBA._0001.data"]; GroupingType="ExtendedSubDetector" ' LArCalibProcessing/UseLArExtendedSubDetGrouping.py  LArCalibProcessing/LArCalib_Ramp_jobOptions.py LArCalibProcessing/LArCalib_Ramp_testing.py
-echoC
-athena.py  -c 'doMonitoring=False; doLArCalibDataQuality=True; CorrectBadChannels=True; ApplyAdHocCorrection=False; GainList=["HIGH"]; PartitionType="EMB"; Partition="EB-EMBA"; PartitionTypeGeneric="EMBPS"; RunNumberList=[174586]; RunNumberFlag=int(RunNumberList[0]); InputDir=" "; FullFileName=["/afs/cern.ch/user/l/larcalib/w0/Test/data11_calib.00174586.calibration_LArElec-Ramp-7s-High-BarrelPS.daq.RAW._lb0000._EB-EMBA._0001.data"]; GroupingType="ExtendedSubDetector" ' LArCalibProcessing/UseLArExtendedSubDetGrouping.py  LArCalibProcessing/LArCalib_Ramp_jobOptions.py LArCalibProcessing/LArCalib_Ramp_testing.py
-echoC
-athena.py -c "rec.doDetailedAuditor=True ; rec.doNameAuditor=True " RecExRecoTest/RecExRecoTest_RTT_empty.py
-echoC
-athena.py -c "rec.doDetailedAuditor=True ; rec.doNameAuditor=True " RecExRecoTest/RecExRecoTest_RTT_empty.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExAnaTest/RecExAnaTest_RTT_notrigger.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExAnaTest/RecExAnaTest_RTT_notrigger.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5 ; doFloatingPointException=True ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " RecExAnaTest/RecExAnaTest_RTT_notrigger.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5 ; doFloatingPointException=True ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " RecExAnaTest/RecExAnaTest_RTT_notrigger.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExAnaTest/RecExAnaTest_RTT_all.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExAnaTest/RecExAnaTest_RTT_all.py
-echoC
-athena.py  --drop-and-reload -c "jp.AthenaCommonFlags.EvtMax=5 ; " RecExAnaTest/RecExAnaTest_RTT_all.py
-echoC
-athena.py  --drop-and-reload -c "jp.AthenaCommonFlags.EvtMax=5 ; " RecExAnaTest/RecExAnaTest_RTT_all.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5 ; doFloatingPointException=True ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " RecExAnaTest/RecExAnaTest_RTT_all.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5 ; doFloatingPointException=True ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " RecExAnaTest/RecExAnaTest_RTT_all.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExRecoTest/RecExRecoTest_RTT_esd.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExRecoTest/RecExRecoTest_RTT_esd.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExCommon/esdtoaod.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExCommon/esdtoaod.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExCommon/aodtotag.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExCommon/aodtotag.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5;rec.doDetailedAuditor=True;jp.AthenaCommonFlags.PoolInputQuery='(EventNumber == 2 || EventNumber == 4)'; rec.doNameAuditor=True" RecExCommon/tagtoaod.py 
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5;rec.doDetailedAuditor=True;jp.AthenaCommonFlags.PoolInputQuery='(EventNumber == 2 || EventNumber == 4)'; rec.doNameAuditor=True" RecExCommon/tagtoaod.py 
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExTrigTest/RecExTrigTest_RTT_esdtrigger.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExTrigTest/RecExTrigTest_RTT_esdtrigger.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExCommon/esdtoaod.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExCommon/esdtoaod.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExCommon/aodtotag.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExCommon/aodtotag.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py D3PDMakerConfig/AODToEgammaD3PD.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py D3PDMakerConfig/AODToEgammaD3PD.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5;jp.AthenaCommonFlags.PoolInputQuery='(EventNumber == 2 || EventNumber == 4)' ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True" RecExCommon/tagtoaod.py 
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5;jp.AthenaCommonFlags.PoolInputQuery='(EventNumber == 2 || EventNumber == 4)' ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True" RecExCommon/tagtoaod.py 
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ;jp.AthenaCommonFlags.FilesInput=['root://eosatlas//eos/atlas/atlascerngroupdisk/phys-rig/pileupSamples/mc12_8TeV.105200.McAtNloJimmy_CT10_ttbar_LeptonFilter.digit.RDO.e1513_s1499_s1504_d700/RDO.01177879._000001.pool.root.1'] " AthenaCommon/MemTraceInclude.py RecExRecoTest/RecExRecoTest_RTT_common.py RecExCommon/rdotobs.py
-echoC
-athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ;jp.AthenaCommonFlags.FilesInput=['root://eosatlas//eos/atlas/atlascerngroupdisk/phys-rig/pileupSamples/mc12_8TeV.105200.McAtNloJimmy_CT10_ttbar_LeptonFilter.digit.RDO.e1513_s1499_s1504_d700/RDO.01177879._000001.pool.root.1'] " AthenaCommon/MemTraceInclude.py RecExRecoTest/RecExRecoTest_RTT_common.py RecExCommon/rdotobs.py
-echoC
-athena.py  -c "rec.AutoConfiguration=['everything']; jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doTruth=False " RecExRecoTest/RecExRecoTest_RTT_common.py RecExCommon/bstoesd.py 
-echoC
-athena.py  -c "rec.AutoConfiguration=['everything']; jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doTruth=False " RecExRecoTest/RecExRecoTest_RTT_common.py RecExCommon/bstoesd.py 
-echoC
-athena.py  -c "rec.AutoConfiguration=['everything']; jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doTruth=False ; rec.doNameAuditor=True " RecExRecoTest/RecExRecoTest_RTT_common.py RecExCommon/esdtoaod.py 
-echoC
-athena.py  -c "rec.AutoConfiguration=['everything']; jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doTruth=False ; rec.doNameAuditor=True " RecExRecoTest/RecExRecoTest_RTT_common.py RecExCommon/esdtoaod.py 
-echoC
-athena.py  -c "rec.AutoConfiguration=['everything']; jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ;  rec.doTruth=False ; rec.doNameAuditor=True " RecExRecoTest/RecExRecoTest_RTT_common.py RecExCommon/aodtotag.py 
-echoC
-athena.py  -c "rec.AutoConfiguration=['everything']; jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ;  rec.doTruth=False ; rec.doNameAuditor=True " RecExRecoTest/RecExRecoTest_RTT_common.py RecExCommon/aodtotag.py 
-echoC
-athena.py  -c "rec.AutoConfiguration=['everything'];jp.AthenaCommonFlags.EvtMax=5;jp.AthenaCommonFlags.PoolInputQuery='(EventNumber == 2 || EventNumber == 4)'; rec.doDetailedAuditor=True ;  rec.doTruth=False ; rec.doNameAuditor=True " RecExCommon/tagtoaod.py 
-echoC
-athena.py  -c "rec.AutoConfiguration=['everything'];jp.AthenaCommonFlags.EvtMax=5;jp.AthenaCommonFlags.PoolInputQuery='(EventNumber == 2 || EventNumber == 4)'; rec.doDetailedAuditor=True ;  rec.doTruth=False ; rec.doNameAuditor=True " RecExCommon/tagtoaod.py 
-echoC
-athena.py TileRecEx/jobOptions_TileCommissioningAtn.py
-echoC
-athena.py TileRecEx/jobOptions_TileCommissioningAtn.py
-echoC
-athena.py TileRecEx/jobOptions_TileCosmicAtn.py
-echoC
-athena.py TileRecEx/jobOptions_TileCosmicAtn.py
+alias athena.py='timeout 30 athena.py'
+###############################################################
+function runTest {
+        echoC
+        athena.py $1
+        SuccessOrNot $? $1
+}
+
+runTest UserDataExamples/UserDataExamples_Writer.py
+runTest UserDataExamples/UserDataExamples_Reader.py
+runTest InDetAlignExample/AlignmentATNSimple.py
+runTest InDetMonitoringATN/jobOptions_cosmics.py
+runTest TileRecEx/jobOptions_TileCommissioningAtn.py
+runTest TileRecEx/jobOptions_TileCosmicAtn.py
+runTest AthExHelloWorld/HelloWorld_ATN.py
+###############################################################
+
 echoC
 athena.py  -c RunNumber=239908 TileRecEx/jobOptions_TileCosmicAtn.py
+SuccessOrNot $? TileRecEx/jobOptions_TileCosmicAtn.py_diff_runnumber
+
 echoC
-athena.py  -c RunNumber=239908 TileRecEx/jobOptions_TileCosmicAtn.py
+athena.py  -c 'doMonitoring=False; runAccumulator=False; doLArCalibDataQuality=True; GainList=["HIGH"]; PartitionType="EMB"; Partition="EB-EMBA"; PartitionTypeGeneric="EMBPS"; RunNumberList=[174585]; RunNumberFlag=int(RunNumberList[0]); InputDir=" "; FullFileName=["/afs/cern.ch/user/l/larcalib/w0/Test/data11_calib.00174585.calibration_LArElec-Pedestal-7s-High-BarrelPS.daq.RAW._lb0000._EB-EMBA._0001.data"]; GroupingType="ExtendedSubDetector" ' LArCalibProcessing/UseLArExtendedSubDetGrouping.py  LArCalibProcessing/LArCalib_PedestalAutoCorr_jobOptions.py LArCalibProcessing/LArCalib_PedestalAutoCorr_testing.py
+SuccessOrNot $? LArCalibProcessing/LArCalib_PedestalAutoCorr_testing.py
+
 echoC
-athena.py AthExHelloWorld/HelloWorld_ATN.py
+athena.py  -c 'doMonitoring=False; doLArCalibDataQuality=True; CorrectBadChannels=True; ApplyAdHocCorrection=False; GainList=["HIGH"]; PartitionType="EMB"; Partition="EB-EMBA"; PartitionTypeGeneric="EMBPS"; RunNumberList=[174586]; RunNumberFlag=int(RunNumberList[0]); InputDir=" "; FullFileName=["/afs/cern.ch/user/l/larcalib/w0/Test/data11_calib.00174586.calibration_LArElec-Ramp-7s-High-BarrelPS.daq.RAW._lb0000._EB-EMBA._0001.data"]; GroupingType="ExtendedSubDetector" ' LArCalibProcessing/UseLArExtendedSubDetGrouping.py  LArCalibProcessing/LArCalib_Ramp_jobOptions.py LArCalibProcessing/LArCalib_Ramp_testing.py
+SuccessOrNot $? LArCalibProcessing/LArCalib_Ramp_testing.py-2
+
 echoC
-athena.py AthExHelloWorld/HelloWorld_ATN.py
+athena.py -c "rec.doDetailedAuditor=True ; rec.doNameAuditor=True " RecExRecoTest/RecExRecoTest_RTT_empty.py
+SuccessOrNot $? RecExRecoTest/RecExRecoTest_RTT_empty.py
+
 echoC
+athena.py  -c "jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExAnaTest/RecExAnaTest_RTT_notrigger.py
+SuccessOrNot $? RecExAnaTest/RecExAnaTest_RTT_notrigger.py
+echoC
+athena.py  -c "jp.AthenaCommonFlags.EvtMax=5 ; doFloatingPointException=True ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " RecExAnaTest/RecExAnaTest_RTT_notrigger.py
+SuccessOrNot $? RecExAnaTest/RecExAnaTest_RTT_notrigger.py
+echoC
+athena.py  -c "jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExAnaTest/RecExAnaTest_RTT_all.py
+SuccessOrNot $? RecExAnaTest/RecExAnaTest_RTT_all.py
+echoC
+athena.py  -c "jp.AthenaCommonFlags.EvtMax=5 ; doFloatingPointException=True ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " RecExAnaTest/RecExAnaTest_RTT_all.py
+SuccessOrNot $? RecExAnaTest/RecExAnaTest_RTT_all.py
+echoC
+athena.py  -c "jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExRecoTest/RecExRecoTest_RTT_esd.py
+SuccessOrNot $? RecExRecoTest/RecExRecoTest_RTT_esd.py
+echoC
+athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExCommon/esdtoaod.py
+SuccessOrNot $? RecExCommon/esdtoaod.py
+echoC
+athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExCommon/aodtotag.py
+SuccessOrNot $? RecExCommon/aodtotag.py
+echoC
+athena.py  -c "jp.AthenaCommonFlags.EvtMax=5;rec.doDetailedAuditor=True;jp.AthenaCommonFlags.PoolInputQuery='(EventNumber == 2 || EventNumber == 4)'; rec.doNameAuditor=True" RecExCommon/tagtoaod.py 
+SuccessOrNot $? RecExCommon/tagtoaod.py
+echoC
+athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExTrigTest/RecExTrigTest_RTT_esdtrigger.py
+SuccessOrNot $? RecExTrigTest/RecExTrigTest_RTT_esdtrigger.py
+echoC
+athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExCommon/esdtoaod.py
+SuccessOrNot $? RecExCommon/esdtoaod.py
+echoC
+athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py RecExCommon/aodtotag.py
+SuccessOrNot $? RecExCommon/aodtotag.py
+echoC
+athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ; rec.doNameAuditor=True " AthenaCommon/MemTraceInclude.py D3PDMakerConfig/AODToEgammaD3PD.py
+SuccessOrNot $? D3PDMakerConfig/AODToEgammaD3PD.py
+echoC
+athena.py  -c "jp.AthenaCommonFlags.EvtMax=5;jp.AthenaCommonFlags.PoolInputQuery='(EventNumber == 2 || EventNumber == 4)' ; rec.doDetailedAuditor=True ; rec.doNameAuditor=True" RecExCommon/tagtoaod.py 
+SuccessOrNot $? RecExCommon/tagtoaod.py
+echoC
+athena.py  -c "jp.AthenaCommonFlags.EvtMax=5; rec.doDetailedAuditor=True ;jp.AthenaCommonFlags.FilesInput=['root://eosatlas//eos/atlas/atlascerngroupdisk/phys-rig/pileupSamples/mc12_8TeV.105200.McAtNloJimmy_CT10_ttbar_LeptonFilter.digit.RDO.e1513_s1499_s1504_d700/RDO.01177879._000001.pool.root.1'] " AthenaCommon/MemTraceInclude.py RecExRecoTest/RecExRecoTest_RTT_common.py RecExCommon/rdotobs.py
+SuccessOrNot $? RecExCommon/rdotobs.py
+echoC
+athena.py  -c "rec.AutoConfiguration=['everything']; jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doTruth=False " RecExRecoTest/RecExRecoTest_RTT_common.py RecExCommon/bstoesd.py 
+SuccessOrNot $? RecExCommon/bstoesd.py
+echoC
+athena.py  -c "rec.AutoConfiguration=['everything']; jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ; rec.doTruth=False ; rec.doNameAuditor=True " RecExRecoTest/RecExRecoTest_RTT_common.py RecExCommon/esdtoaod.py 
+SuccessOrNot $? RecExCommon/esdtoaod.py
+echoC
+athena.py  --drop-and-reload -c "jp.AthenaCommonFlags.EvtMax=5 ; " RecExAnaTest/RecExAnaTest_RTT_all.py
+SuccessOrNot $? RecExAnaTest/RecExAnaTest_RTT_all.py
+echoC
+athena.py  -c "rec.AutoConfiguration=['everything']; jp.AthenaCommonFlags.EvtMax=5 ; rec.doDetailedAuditor=True ;  rec.doTruth=False ; rec.doNameAuditor=True " RecExRecoTest/RecExRecoTest_RTT_common.py RecExCommon/aodtotag.py 
+SuccessOrNot $? RecExCommon/aodtotag.py
+echoC
+athena.py  -c "rec.AutoConfiguration=['everything'];jp.AthenaCommonFlags.EvtMax=5;jp.AthenaCommonFlags.PoolInputQuery='(EventNumber == 2 || EventNumber == 4)'; rec.doDetailedAuditor=True ;  rec.doTruth=False ; rec.doNameAuditor=True " RecExCommon/tagtoaod.py 
+SuccessOrNot $? RecExCommon/tagtoaod.py 
diff --git a/rel_6/Testing/AtlasConditionsTests/AtlasConditionsTests b/rel_6/Testing/AtlasConditionsTests/AtlasConditionsTests
--- a/rel_6/Testing/AtlasConditionsTests/AtlasConditionsTests
+++ b/rel_6/Testing/AtlasConditionsTests/AtlasConditionsTests
@@ -1,7 +1,23 @@
 #!/bin/sh
+
+#!/bin/sh
 export AtlasVersion=AtlasConditions
+function SuccessOrNot {
+        if [ $1 -eq 0 ]; then
+          echo "$(tput setaf 2) $2 succeeded" >> PASSorFAIL
+        else
+          echo "$(tput setaf 1) $2 FAILED" >> PASSorFAIL
+        fi
+}
+
 alias echoC='echo "$(tput setaf 1)$(tput setab 7) Starting new test... $(tput sgr 0)"'
-echoC
-timeout 10 athena.py InDetGeometryValidation/ReadTRT_DetectorElements_jobOptions.py
-echoC
-timeout 10 athena.py InDetGeometryValidation/ReadSiDetectorElements_jobOptions.py
+alias athena.py='timeout 10 athena.py'
+
+function runTest {
+        echoC
+        athena.py $1
+        SuccessOrNot $? $1
+}
+
+runTest InDetGeometryValidation/ReadTRT_DetectorElements_jobOptions.py
+runTest InDetGeometryValidation/ReadSiDetectorElements_jobOptions.py
diff --git a/rel_6/Testing/AtlasCoreTests/AtlasCoreTests b/rel_6/Testing/AtlasCoreTests/AtlasCoreTests
--- a/rel_6/Testing/AtlasCoreTests/AtlasCoreTests
+++ b/rel_6/Testing/AtlasCoreTests/AtlasCoreTests
@@ -1,12 +1,23 @@
 #!/bin/sh
 export AtlasVersion=AtlasCore
+function SuccessOrNot {
+	if [ $1 -eq 0 ]; then
+    	  echo "$(tput setaf 2) $2 succeeded" >> PASSorFAIL
+	else
+   	  echo "$(tput setaf 1) $2 FAILED" >> PASSorFAIL
+	fi
+}
 
 alias echoC='echo "$(tput setaf 1)$(tput setab 7) Starting new test... $(tput sgr 0)"'
-echoC
-athena.py AthExHelloWorld/HelloWorldOptions.py
-echoC
-athena.py AthExHelloWorld/HelloWorld_ATN.py
-echoC
-athena.py AthenaServices/SimplePOSIXTimeKeeperSvc_test.py
-echoC
-athena.py AthenaServices/AthDictLoaderSvc_test.py 
+alias athena.py='timeout 100 athena.py'
+
+function runTest {
+	echoC
+	athena.py $1
+	SuccessOrNot $? $1
+}
+
+runTest AthExHelloWorld/HelloWorldOptions.py
+runTest AthExHelloWorld/HelloWorld_ATN.py
+runTest AthenaServices/SimplePOSIXTimeKeeperSvc_test.py
+runTest AthenaServices/AthDictLoaderSvc_test.py 
diff --git a/rel_6/Testing/AtlasEventTests/AtlasEventTests b/rel_6/Testing/AtlasEventTests/AtlasEventTests
--- a/rel_6/Testing/AtlasEventTests/AtlasEventTests
+++ b/rel_6/Testing/AtlasEventTests/AtlasEventTests
@@ -1,12 +1,24 @@
 #!/bin/sh
-export AtlasVersion=AtlasEvent
+#!/bin/sh
+export AtlasVersion=AtlasCore
+function SuccessOrNot {
+        if [ $1 -eq 0 ]; then
+          echo "$(tput setaf 2) $2 succeeded" >> PASSorFAIL
+        else
+          echo "$(tput setaf 1) $2 FAILED" >> PASSorFAIL
+        fi
+}
+
 alias echoC='echo "$(tput setaf 1)$(tput setab 7) Starting new test... $(tput sgr 0)"'
-echoC
-athena.py AthenaDBTestRec/ReadRefDBExample.py
-echoC
-athena.py -s AthenaServices/MultiplePass_test.py
-echoC
-athena.py -s EventLoopTest/ByteStreamReadTest.py
-echoC
-athena.py -s AthenaServices/MixingEventSelector_test.py
+alias athena.py='timeout 100 athena.py'
+
+function runTest {
+        echoC
+        athena.py $1
+        SuccessOrNot $? $1
+}
+runTest AthenaDBTestRec/ReadRefDBExample.py
+runTest AthenaServices/MultiplePass_test.py
+runTest EventLoopTest/ByteStreamReadTest.py
+runTest AthenaServices/MixingEventSelector_test.py
 
diff --git a/rel_6/Testing/AtlasSimulationTests/AtlasSimulationTests b/rel_6/Testing/AtlasSimulationTests/AtlasSimulationTests
--- a/rel_6/Testing/AtlasSimulationTests/AtlasSimulationTests
+++ b/rel_6/Testing/AtlasSimulationTests/AtlasSimulationTests
@@ -1,35 +1,28 @@
 #!/bin/sh
 export AtlasVersion=AtlasSimulation
+
+function SuccessOrNot {
+        if [ $1 -eq 0 ]; then
+          echo "$(tput setaf 2) $2 succeeded" >> PASSorFAIL
+        else
+          echo "$(tput setaf 1) $2 FAILED" >> PASSorFAIL
+        fi
+}
+
 alias echoC='echo "$(tput setaf 1)$(tput setab 7) Starting new test... $(tput sgr 0)"'
-echoC
-timeout 10 athena.py CaloDigEx/CaloDigEx.py
-echoC
-timeout 10 athena.py CaloDigEx/CaloDigEx.py
-echoC
-timeout 10 athena.py CaloSimEx/CaloSimEx.py
-echoC
-timeout 10 athena.py CaloSimEx/CaloSimEx.py
-echoC
-athena.py  -s Digitization/DigitizationRTT_all_noLVL1.py
-echoC
-athena.py  -s Digitization/DigitizationRTT_all_noLVL1.py
-echoC
-athena.py  Digitization/NightlyPileUp.py
-echoC
-athena.py  Digitization/NightlyPileUp.py
-echoC
-athena.py G4AtlasApps/jobOptions.G4Atlas.py
-echoC
-athena.py G4AtlasApps/jobOptions.G4Atlas.py
-echoC
-athena.py G4AtlasApps/jobOptions.G4Atlas_ReadEvgen.py
-echoC
-athena.py G4AtlasApps/jobOptions.G4Atlas_ReadEvgen.py
-echoC
-athena.py G4AtlasApps/jobOptions.G4Cosmic.py
-echoC
-athena.py G4AtlasApps/jobOptions.G4Cosmic.py
-echoC
-athena.py  TileSimEx/jobOptions_TileTB_Sim.py 
-echoC
-athena.py  TileSimEx/jobOptions_TileTB_Sim.py 
+alias athena.py='timeout 30 athena.py'
+
+function runTest {
+        echoC
+        athena.py $1
+        SuccessOrNot $? $1
+}
+
+runTest CaloDigEx/CaloDigEx.py
+runTest CaloSimEx/CaloSimEx.py
+runTest Digitization/DigitizationRTT_all_noLVL1.py
+runTest Digitization/NightlyPileUp.py
+runTest G4AtlasApps/jobOptions.G4Atlas.py
+runTest G4AtlasApps/jobOptions.G4Atlas_ReadEvgen.py
+runTest G4AtlasApps/jobOptions.G4Cosmic.py
+runTest TileSimEx/jobOptions_TileTB_Sim.py 
